version: '1.0.0'

networks:
  laravel: #creara la red llamada course_laravel, $nombrecarpeta_$nombredered

services:


  apache:
    build:
      context: .
      dockerfile: apache.dockerfile
    container_name: apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel
  php:
    image: php:7.4.33-fpm-alpine
    container_name: php
    networks:
      - laravel

  mysql:
    image: mysql:5.7.43
    container_name: mysql
    environment:
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel